41x4dyt
baaspoolsllc/nodies_monitoring pull request #2
Opened 2022-10-26 14:06 UTC by YuppiePF

## Issue ticket number and link

https://app.clickup.com/t/41x4dyt

## Description

Decouple exporter services from monitoring services.

## Type of change

Please delete option that is not relevant.

- [X] New feature (non-breaking change which adds functionality)

2022-10-26 22:43 UTC, tohoPF commented
We shouldn't assume root. Lets use default docker group and update file permissions. It would be a good idea to also include chown and chmod steps in the setup.py ..

2022-10-26 22:46 UTC, tohoPF commented on clients/bcexporter/config/Config.py
> +        with open("./config/chains.json", "r") as stream:
Let's use[ pathlib ](https://docs.python.org/3/library/pathlib.html)

2022-10-26 22:50 UTC, tohoPF requested changes

2022-10-26 22:50 UTC, tohoPF commented on templates/clients/docker-compose.yml
> +    user: "0:0"
remove hardcoded root user and change file permissions to use the docker group. add a step in setup.py that does this.

2022-10-26 22:50 UTC, tohoPF commented on clients/bcexporter/config/Config.py
> +        with open("./config/chains.json", "r") as stream:
Let's use pathlib

2022-10-26 22:50 UTC, tohoPF commented on variables.py
> +        newdict["datasources"][0]["url"] = 'http://' + os.getenv("MONITORING_ENDPOINT") + ':' + os.getenv(f'{source.upper()}_PORT')
use urllib

2022-10-26 22:50 UTC, tohoPF commented on variables.py
> +    newdict["clients"][0]["url"] = 'http://' + os.getenv('MONITORING_ENDPOINT') + ':' + os.getenv('LOKI_PORT') + '/loki/api/v1/push'
use urllib

2022-10-26 22:50 UTC, tohoPF commented on variables.py
> +    newdict["clients"][0]["url"] = 'https://' + os.getenv('MONITORING_ENDPOINT') + ':' + os.getenv('LOKI_PORT') + '/loki/api/v1/push'
use urllib

2022-10-27 03:11 UTC, PoktBlade commented on clients/bcexporter/config/Config.py
> +        with open("./config/chains.json", "r") as stream:
Is chains.json mounted yet in docker-compose? It should not be expected that chains.json is part of the python build, given it's a config file that should be editable and changeable

2022-10-27 03:13 UTC, nodiesBlade commented on variables.py
>  import yaml
Whole file needs to be cleaned up. Variables.py should be renamed to setup.py

Furthermore, there should be clear, concise code of each setup component, and there is also DRY being broken here with how we load and replace files in general.

Script like coding is fine, but if we're going to do it in a high level language, let's take advantage of it.

2022-10-27 03:14 UTC, PoktBlade commented on variables.py
>      with open(template_client_bcexporter, "r") as f:
example of DRY when loading files. just to replace a yaml var

2022-10-27 03:17 UTC, PoktBlade commented on templates/clients/docker-compose.yml
> +#  cadvisor:
Why did we remove cadvisor?

2022-10-28 04:54 UTC, closed without merging